[package]
name = "mocking-and-testing"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
anyhow = "1.0"
schema-registry = { path = "../../schema-registry", features = ["testing"] }